---
title: "Documentation"
subtitle: "To Do"
output: html_notebook
---

# Help files

+ <span style="color:red">**FLCore::FLPar()**</span>  the function does not seem to have any validation on the names of the parameters. Perhaps this is by design so you can include anything you want, however users do need a list of parameters that are 'understood' by functions later on in the code. Not sure how this would work if FLPar is a generic function. For MYDAS would probably be best to list the parameters relevant to MYDAS in one of the Vignettes

+ <span style="color:green">**FLife::lhPar()**</span> all the parameters need to be listed and it would be nice if the default values or equations and references for filling in missing values would be given here as well <span style="color:red">(in the conditioning vignette this was nicely documented but it would be good to see this in the helpfile as well)</span>

+ <span style="color:green">**FLife::lhEql()** works now

## Time Series Dynamics 

+ <span style="color:red">**more explicit**</span> about what is going on here. You are simulating a time series of F and apply that to the operating model, without feedback (F has already been decided) and without recruitment deviations etc.

+ <span style="color:red">**Stochasticity**</span> Now we are including recruitment variability

+ <span style="color:green">**FLCore::rlnoise()**</span> can not find rnoise

+ <span style="color:green">**residuals**</span> seems to be depreciated in fwd(); now called deviances. <span style="color:green">changed</span>

## Exploring sensitivity of equilibrium reference points 

+ <span style="color:green">**nice**</span>  to include the code in example-1.R in the conditioning vignette; just to show how you can vary the lh parameters.

## Turbot OM 

Include in  package then the other vignettes can skip all the parts about condidtioning the OM

+ <span style="color:green">**mydas_turbot**</span> conditioning vignette
+ <span style="color:green">**dataset**</span> remove OM conditioning from other vignettes and replace with data(om)
+ <span style="color:green">**documentation**</span> add as dataset


# Vignettes

## Mydas_oem

+ <span style="color:red">**Catch per unit effort**</span> you start by generating an unbiased index of total biomass using the function stock(). It is kind of difficult to figure out what this function does. I think it is total stock biomass. Might be handy to mention this.


+ <span style="color:red">**Effort creep**</span> if I understand it correctly the trend() function you define here increases catchability by 2% per year in this example. "Model an increase in catchabilty, e.g. due to an increase in catchability. In this example the catchability increases by 2% per year"

+ <span style="color:red">**%=%**</span> I am always a bit confused by these special operators and find it difficult to get help. Could you explain what it does (I think it makes the value of stock(om) be 1). Neat. Anway, it is difficult to find a balance between how much to explain about R coding and how much you can assume. Just highlighting where my comfort zone ends....

## Mydas_sra

+ <span style="color:red">**Mydas::popdyn() function**</span>  - needs documentation. Can (presumably) refer to lhPar but also need to explain what all the reference points are and how they are calculated. Variable names like lc are particulary tricky as they can mean different things, depending on which length-based method you use (it can be length at 50% of modal abundance or length at full selection).
+ <span style="color:red">**A bit more explanation**</span>  please of the steps: first you fit an assessment model to the OM with perfect knowledge. This is an important step to validate that the model makes sense
+ <span style="color:red">**setMP()**</span>  - explain what is going on here: a bit of documentation on what a biodynamic model does or a reference to a separate vignette
+ <span style="color:red">**explain**</span>  why you fit the model to the years 20:54 only
+ <span style="color:red">**second model**</span>, explain that by using only the first two and last two values of the index, you essentially (or exactly?) have a dbsra model
+ <span style="color:red">**explain**</span>  why it gives the same result as the MP run
+ <span style="color:red">**explain**</span>  that sra-2 is where you give an incorrect estimate of the final biomass (b0)

## mydas_length

+ <span style="color:red">**mydas::omSmry()**</span>  - output needs to be documented in help file, what do all the statistics mean and how are they calculated?
+ <span style="color:red">**mnLen**</span>  is the mean length in the catch, I understand that the mean length Z methods takes the mean length of individuals larger than Lc as an input (where Lc is the length at full selection). This is not the exactly the same as the mean length in the catch, unless you have knife-edge selectivity.
+ <span style="color:red">**mydas:::mlz()**</span>  not documented, e.g. how do you decide on the number of break points?
+ <span style="color:red">**output (res)**</span>  is typical mlz output but difficult to interpret. Is it easy to plot the estimated mean length time series from MLZ against the OM? Also it should be possible to plot the F (or Z) in each time block and compare to OM?
+ <span style="color:red">**mydas::lenSample**</span>  - helpfile incomplete
+ <span style="color:red">**lbspr method**</span>  - I presume this will become part of the package?
+ <span style="color:red">**Similar to mlz**</span>  is it possible to plot the outpute of lbspr against the om, e.g. F/M?

## Mydas_mse
+ <span style="color:red">**explain**</span>  the first step is just adding noise to the OM and no model, no feedback at this stage. Explain why you are doing this.

### Harvest Control Rule 
+ <span style="color:red">**explain**</span>  that this is an example of a tuna? hcr. 
+ <span style="color:red">**FLCore:fmle**</span>  - no help file
+ <span style="color:red">**error now in mseXSA**</span>  that I didn't get last week:
Error in mseXSA(oms[["Projection"]], eq, mp, xsaControl, rf = rf, sr_deviances = srDev,  : 
  unused arguments (sr_deviances = srDev, u_deviances = uDev)
+ <span style="color:red">**error in mseMPB2**</span>
Error in read.table(paste("pella.rep", sep = ""), skip = 18, header = T) : no lines available in input

